### ISSUE TITLE
add 'ssn' module

### ISSUE THREAD

**Issue by jiro4989** [jiro4989/faker#26]

**Comment by fishnibble** [comment]
For SSN. What country format should we support? I'm only familiar with American SSN. However I'm willing to looking other formats. I can start with USA based ssn and build off of that.

**Comment by jiro4989** [comment]
> For SSN. What country format should we support?

I'm thinking only in English for now.
Because it's hard to support SSNs in every language.

**Comment by fishnibble** [comment]
> > For SSN. What country format should we support?
> 
> I'm thinking only in English for now. Because it's hard to support SSNs in every language.

Okay cool! I'll start on it sometime this weekend!

**Comment by fishnibble** [comment]
#83 Let me know if this is okay! :)

**Comment by jiro4989** [comment]
#83 was merged.
