### ISSUE TITLE
fake password

### ISSUE THREAD

**Issue by enthus1ast** [jiro4989/faker#70]
A fake password would be nice! Could maybe generate from the top 1000? Passwords, paired with an integer, or part of a name...

**Comment by jiro4989** [comment]
Is the password top 1000 this ?

https://github.com/danielmiessler/SecLists/blob/master/Passwords/Common-Credentials/10-million-password-list-top-1000.txt

**Comment by jiro4989** [comment]
@enthus1ast  I added a new procedure `dangerPassword` to `develop` branch.
[Code](https://github.com/jiro4989/faker/commit/4244adc80b26a2c35d7bc1c6bcf7f3f78828b9ac#diff-7acb8fb47e675a387f61c42dbb8e0fb730e6ccfd75155dbc3d1824d7269ecd16R1030)

Try use this procedure. And tell me your feedback.

```bash
git clone https://github.com/jiro4989/faker
git checkout develop
nim c -r ./src/faker/provider/misc/misc_en_US.nim
```
